"""Legacy oopz package backed by oopz_sdk."""

from oopz_sdk.version import __version__

from .client import EVENT_AUTH, EVENT_CHAT_MESSAGE, EVENT_HEARTBEAT, EVENT_SERVER_ID, OopzClient
from .config import (
    AutoRecallConfig,
    DEFAULT_HEADERS,
    HeartbeatConfig,
    OopzConfig,
    ProxyConfig,
    RetryConfig,
)
from .exceptions import (
    OopzApiError,
    OopzAuthError,
    OopzConnectionError,
    OopzError,
    OopzParseError,
    OopzRateLimitError,
    OopzTransportError,
)
from .models import (
    ApiResponse,
    Area,
    AreaBlock,
    AreaBlocksResult,
    AreaInfo,
    AreaMembersPage,
    Attachment,
    AudioAttachment,
    BaseModel,
    Channel,
    ChannelGroup,
    ChannelGroupsResult,
    ChannelInfo,
    ChannelMessage,
    ChannelSetting,
    ChatMessageEvent,
    DailySpeechResult,
    Event,
    ImageAttachment,
    JoinedAreasResult,
    LifecycleEvent,
    Member,
    Message,
    MessageEvent,
    MessageListResult,
    MessageSendResult,
    OperationResult,
    PersonDetail,
    PersonInfo,
    PrivateSessionResult,
    SelfDetail,
    UploadAttachment,
    UploadResult,
    VoiceChannelMember,
    VoiceChannelMembersResult,
)
from .sender import OopzSender
from .signer import ClientMessageIdGenerator, Signer, request_id, timestamp_ms, timestamp_us
from .upload import UploadMixin, get_image_info

__all__ = [
    "ApiResponse",
    "Area",
    "AreaBlock",
    "AreaBlocksResult",
    "AreaInfo",
    "AreaMembersPage",
    "Attachment",
    "AudioAttachment",
    "AutoRecallConfig",
    "BaseModel",
    "Channel",
    "ChannelGroup",
    "ChannelGroupsResult",
    "ChannelInfo",
    "ChannelMessage",
    "ChannelSetting",
    "ChatMessageEvent",
    "ClientMessageIdGenerator",
    "DEFAULT_HEADERS",
    "DailySpeechResult",
    "EVENT_AUTH",
    "EVENT_CHAT_MESSAGE",
    "EVENT_HEARTBEAT",
    "EVENT_SERVER_ID",
    "Event",
    "HeartbeatConfig",
    "ImageAttachment",
    "JoinedAreasResult",
    "LifecycleEvent",
    "Member",
    "Message",
    "MessageEvent",
    "MessageListResult",
    "MessageSendResult",
    "OopzApiError",
    "OopzAuthError",
    "OopzClient",
    "OopzConfig",
    "OopzConnectionError",
    "OopzError",
    "OopzParseError",
    "OopzRateLimitError",
    "OopzSender",
    "OopzTransportError",
    "OperationResult",
    "PersonDetail",
    "PersonInfo",
    "PrivateSessionResult",
    "ProxyConfig",
    "RetryConfig",
    "SelfDetail",
    "Signer",
    "UploadAttachment",
    "UploadMixin",
    "UploadResult",
    "VoiceChannelMember",
    "VoiceChannelMembersResult",
    "__version__",
    "get_image_info",
    "request_id",
    "timestamp_ms",
    "timestamp_us",
]
