"""Legacy model exports backed by oopz_sdk."""

from __future__ import annotations

from oopz_sdk.models import (
    ApiResponse,
    Area,
    AreaBlock,
    AreaBlocksResult,
    AreaInfo,
    AreaMembersPage,
    Attachment,
    AudioAttachment,
    BaseModel,
    Channel,
    ChannelGroup,
    ChannelGroupsResult,
    ChannelInfo,
    ChannelMessage,
    ChannelSetting,
    ChatMessageEvent,
    DailySpeechResult,
    Event,
    ImageAttachment,
    JoinedAreasResult,
    LifecycleEvent,
    Member,
    Message,
    MessageEvent,
    MessageListResult,
    MessageSendResult,
    OperationResult,
    PersonDetail,
    PrivateSessionResult,
    SelfDetail,
    UploadAttachment,
    UploadResult,
    VoiceChannelMember,
    VoiceChannelMembersResult,
)

JsonObject = dict[str, object]
JsonList = list[object]
PersonInfo = Member

__all__ = [
    "ApiResponse",
    "Area",
    "AreaBlock",
    "AreaBlocksResult",
    "AreaInfo",
    "AreaMembersPage",
    "Attachment",
    "AudioAttachment",
    "BaseModel",
    "Channel",
    "ChannelGroup",
    "ChannelGroupsResult",
    "ChannelInfo",
    "ChannelMessage",
    "ChannelSetting",
    "ChatMessageEvent",
    "DailySpeechResult",
    "Event",
    "ImageAttachment",
    "JoinedAreasResult",
    "JsonList",
    "JsonObject",
    "LifecycleEvent",
    "Member",
    "Message",
    "MessageEvent",
    "MessageListResult",
    "MessageSendResult",
    "OperationResult",
    "PersonDetail",
    "PersonInfo",
    "PrivateSessionResult",
    "SelfDetail",
    "UploadAttachment",
    "UploadResult",
    "VoiceChannelMember",
    "VoiceChannelMembersResult",
]
